### ISSUE TITLE
Publish no longer starts automatically

### ISSUE THREAD

**Issue by MatthewSteeples** [microsoft/windows-dev-center-vsts-extension#109]
We've not changed anything in our build pipelines as far as I'm aware, but now when looking to publish a new version of our app the Submission gets created but then we have to go into the Partner dashboard and submit it to the store. This doesn't seem to happen automatically anymore.

**Comment by kevcrooks** [comment]
We have the same issue, when turning on "polling" for the release, the pipeline step fails with the following errors:
```
2024-03-19T16:27:40.0512735Z Polling submission...
2024-03-19T16:27:43.0198820Z Submission status for "applications/[AAAA]/submissions/[9999]"CommitStarted
2024-03-19T16:32:49.3017114Z Errors occurred in request
2024-03-19T16:32:49.3023983Z    [InvalidParameterValue]  Error. Request it is not IngestionWeb or IngestionApi. applicationId = [9999], submissionId = [9999], The ClientIdentifier = IngestionAPIv1Worker
2024-03-19T16:32:49.3074712Z ##[error]Submission status for "applications/[AAAA]/submissions/[9999]" failed with CommitFailed
2024-03-19T16:32:49.3088106Z ##[error]Reported errors: 
2024-03-19T16:32:49.3089860Z ##[error]   InvalidParameterValue: Error. Request it is not IngestionWeb or IngestionApi. applicationId = [9999], submissionId = [9999], The ClientIdentifier = IngestionAPIv1Worker
2024-03-19T16:32:49.3094567Z ##[error]Error: Commit failed
    at D:\a\_tasks\store-publish_8e70da9d-532d-4416-a07f-5ec10f84339f\0.10.32\common\apiHelper.js:230:19
    at _fulfilled (D:\a\_tasks\store-publish_8e70da9d-532d-4416-a07f-5ec10f84339f\0.10.32\node_modules\q\q.js:854:54)
    at D:\a\_tasks\store-publish_8e70da9d-532d-4416-a07f-5ec10f84339f\0.10.32\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (D:\a\_tasks\store-publish_8e70da9d-532d-4416-a07f-5ec10f84339f\0.10.32\node_modules\q\q.js:816:13)
    at D:\a\_tasks\store-publish_8e70da9d-532d-4416-a07f-5ec10f84339f\0.10.32\node_modules\q\q.js:624:44
    at runSingle (D:\a\_tasks\store-publish_8e70da9d-532d-4416-a07f-5ec10f84339f\0.10.32\node_modules\q\q.js:137:13)
    at flush (D:\a\_tasks\store-publish_8e70da9d-532d-4416-a07f-5ec10f84339f\0.10.32\node_modules\q\q.js:125:13)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
2024-03-19T16:32:49.3097544Z ##[error]Error: Commit failed
```

**Comment by CheeryLee** [comment]
I encounter [the same error](https://github.com/microsoft/StoreBroker/issues/249) as @kevcrooks mentioned but using StoreBroker stuff. Seems like this is Partner Center dev team bug.
