### ISSUE TITLE
You have too many Windows Phone 8.1 packages for this app

### ISSUE THREAD

**Issue by azchohfi** [Microsoft/windows-dev-center-vsts-extension#16]
I'm not able to deploy a Windows Phone 8.1 app to the store.
Task Version: 0.7.996

`
2016-11-01T18:43:56.1675363Z ##[section]Starting: Publish $(System.DefaultWorkingDirectory)/BUILD_CI/drop/xxxx/AppPackages/xxxxx_*_ARM.appxupload
2016-11-01T18:43:56.2137084Z ==============================================================================
2016-11-01T18:43:56.2137084Z Task         : Windows Store - Publish
2016-11-01T18:43:56.2137084Z Description  : Publish your app to the Windows Store
2016-11-01T18:43:56.2137084Z Version      : 0.7.996
2016-11-01T18:43:56.2137084Z Author       : Microsoft Corporation
2016-11-01T18:43:56.2137084Z Help         : 
2016-11-01T18:43:56.2137084Z ==============================================================================
2016-11-01T18:43:58.0700046Z bd178ce2-b641-421e-b068-21b679b9b821 exists true
2016-11-01T18:43:58.0800039Z Authenticating...
2016-11-01T18:43:58.0800039Z Authenticating with server...
2016-11-01T18:43:58.2868849Z Obtaining app information...
2016-11-01T18:43:59.0326803Z Creating submission...
2016-11-01T18:44:08.0828718Z Updating submission...
2016-11-01T18:44:09.4300151Z Creating zip file...
2016-11-01T18:44:09.4450083Z Uploading zip file...
2016-11-01T18:44:09.6660078Z 	Uploading block 0 (ID MWE2NzlkNmYwNzVhNDVlZDhkNzk0ODdmOGJlZTc4NTctMDAwMDAw)
2016-11-01T18:44:09.8410170Z 	Uploading block 1 (ID MWE2NzlkNmYwNzVhNDVlZDhkNzk0ODdmOGJlZTc4NTctMDAwMDAx)
2016-11-01T18:44:09.8770182Z 	Uploading block 2 (ID MWE2NzlkNmYwNzVhNDVlZDhkNzk0ODdmOGJlZTc4NTctMDAwMDAy)
2016-11-01T18:44:09.9770084Z 	... All blocks uploaded.
2016-11-01T18:44:10.0070081Z Committing submission...
2016-11-01T18:44:13.1564604Z Polling submission...
2016-11-01T18:44:14.1428773Z Submission 1152921504625903234 status for App 9NBLGGH439LM: CommitStarted
2016-11-01T18:44:25.1474328Z Submission 1152921504625903234 status for App 9NBLGGH439LM: CommitStarted
2016-11-01T18:44:37.2208378Z Submission 1152921504625903234 status for App 9NBLGGH439LM: CommitStarted
2016-11-01T18:44:48.0818150Z Submission 1152921504625903234 status for App 9NBLGGH439LM: CommitStarted
2016-11-01T18:45:00.2512600Z Submission 1152921504625903234 status for App 9NBLGGH439LM: CommitStarted
2016-11-01T18:45:11.1125229Z Submission 1152921504625903234 status for App 9NBLGGH439LM: CommitStarted
2016-11-01T18:45:23.1545579Z ##[error]Submission 1152921504625903234 status for App 9NBLGGH439LM:  failed with CommitFailed
2016-11-01T18:45:23.1545579Z ##[error]Reported errors: 
2016-11-01T18:45:23.1545579Z ##[error]	 InvalidParameterValue: You have too many Windows Phone 8.1 packages for this app. For .appx or .appxbundle package types, you can only submit one package. For .xap, you can submit more than one, but you can't include multiple package types.
2016-11-01T18:45:23.1595572Z ##[error]	 InvalidParameterValue: You’ve uploaded another package with the same properties as this one. When this submission is published, the other package will replace this one.
2016-11-01T18:45:23.1605577Z ##[error]Error: Commit failed
2016-11-01T18:45:23.1605577Z     at C:\a\_tasks\store-publish_8e70da9d-532d-4416-a07f-5ec10f84339f\0.7.996\publish.js:605:19
2016-11-01T18:45:23.1605577Z     at _fulfilled (C:\a\_tasks\store-publish_8e70da9d-532d-4416-a07f-5ec10f84339f\0.7.996\node_modules\q\q.js:834:54)
2016-11-01T18:45:23.1605577Z     at self.promiseDispatch.done (C:\a\_tasks\store-publish_8e70da9d-532d-4416-a07f-5ec10f84339f\0.7.996\node_modules\q\q.js:863:30)
2016-11-01T18:45:23.1605577Z     at Promise.promise.promiseDispatch (C:\a\_tasks\store-publish_8e70da9d-532d-4416-a07f-5ec10f84339f\0.7.996\node_modules\q\q.js:796:13)
2016-11-01T18:45:23.1605577Z     at C:\a\_tasks\store-publish_8e70da9d-532d-4416-a07f-5ec10f84339f\0.7.996\node_modules\q\q.js:604:44
2016-11-01T18:45:23.1605577Z     at runSingle (C:\a\_tasks\store-publish_8e70da9d-532d-4416-a07f-5ec10f84339f\0.7.996\node_modules\q\q.js:137:13)
2016-11-01T18:45:23.1605577Z     at flush (C:\a\_tasks\store-publish_8e70da9d-532d-4416-a07f-5ec10f84339f\0.7.996\node_modules\q\q.js:125:13)
2016-11-01T18:45:23.1605577Z     at _combinedTickCallback (internal/process/next_tick.js:67:7)
2016-11-01T18:45:23.1605577Z     at process._tickCallback (internal/process/next_tick.js:98:9)
2016-11-01T18:45:23.1615578Z ##[error]Error: Commit failed
2016-11-01T18:45:23.1685579Z ##[section]Finishing: Publish $(System.DefaultWorkingDirectory)/BUILD_CI/drop/xxxx/AppPackages/xxxxx_*_ARM.appxupload
`

![image](https://cloud.githubusercontent.com/assets/527713/19903388/acff0138-a055-11e6-8e6b-385cabe56b23.png)

This creates the new Submission on the store, but it does not delete/replace the old package, as I expect for a Windows Phone 8.1 App.

Is this scenario supposed to work? If so, is there a workaround? I'm ore than available to provide additional feedback.

**Comment by elber99** [comment]
Hi, the error explains the issue:

InvalidParameterValue: You have too many Windows Phone 8.1 packages for this app. For .appx or .appxbundle package types, you can only submit one package. For .xap, you can submit more than one, but you can't include multiple package types. 2016-11-01T18:45:23.1595572Z ##[error] InvalidParameterValue: You’ve uploaded another package with the same properties as this one. When this submission is published, the other package will replace this one. 2016-11-01T18:45:23

Bernardo Zamora
Microsoft

**Comment by azchohfi** [comment]
I understand the error message, but that's blocking me from having a CD environment for a Windows Phone 8.1 App. There should be a checkbox or something that removes the old package.
This behaviour is failing the Release on VSTS and making me manually go to the dev center, delete the old version from the incomplete submission and finish it's submission. I understand the problem, I just think that it should handle this situation automating what I'm doing manually now.

**Comment by elendil326** [comment]
Hello @azchohfi, sorry for the late response. I just confirmed with the Windows Store team and the particular behavior for Windows 8.1 packages is that only one package can exist in the store.

The extension itself supports multiple packages to be uploaded, as other platforms support having multiple packages in a given time. I will mark this as a suggestion to add an option to delete all old packages for the same platform and put it on our backlog.

Feel free to reopen the issue if this does not help.

**Comment by eNeRGy164** [comment]
I'm experiencing the same issue. Would be nice to support Windows 8.1 deployments.

**Comment by kp101090** [comment]
@eNeRGy164  @azchohfi We have implemented this functionality in the extension. There is a checkbox named 'Delete Packages' using which you can specify how many packages you want to keep in Dev Center. Can you check it out? 
Regardless, thank you very much for your suggestion and patience!

**Comment by eNeRGy164** [comment]
I'm experiencing issues with the installation of the 0.9.4. extension in the on-premise TFS project collection where the 0.9.3 extension was installed before. (Clean install on another project collection just works fine). So it may take some time to get back on this.

**Comment by eNeRGy164** [comment]
TFS cacheing is over, it works!
