### ISSUE TITLE
Unexpected token =

### ISSUE THREAD

**Issue by mlowrancejha** [Microsoft/windows-dev-center-vsts-extension#59]
I am receiving the error message:

Unexpected token =

This looks like a node.js issue to me, but I couldn't find anywhere that lists any node.js version requirements?  This is an onsite TFS build server, it is running node 8.9.4.

I'm not sure what else to look at.  I haven't been able to successfully complete a Publish or Flight task, they both end with the same error.

Below is the logging output of the build with system.debug = true

Thanks!

Matt

2018-09-19T14:20:26.4144173Z Set workingFolder to default: C:\agent2\tasks\store-flight\0.2.22\local
 
2018-09-19T14:20:27.2738000Z ##[debug]agent.workFolder=e:\builds\agent02
 
2018-09-19T14:20:27.2894236Z ##[debug]loading inputs and endpoints
 
2018-09-19T14:20:27.2894236Z ##[debug]loading ENDPOINT_AUTH_1143A35E-10B8-441C-9A05-6A20AB0120E7
 
2018-09-19T14:20:27.2894236Z ##[debug]loading ENDPOINT_AUTH_3306CACE-E67A-4512-AF8A-7D35E0E733D0
 
2018-09-19T14:20:27.2894236Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
 
2018-09-19T14:20:27.2894236Z ##[debug]loading INPUT_APPID
 
2018-09-19T14:20:27.2894236Z ##[debug]loading INPUT_APPNAME
 
2018-09-19T14:20:27.2894236Z ##[debug]loading INPUT_DELETEPACKAGES
 
2018-09-19T14:20:27.2894236Z ##[debug]loading INPUT_FLIGHTNAME
 
2018-09-19T14:20:27.2894236Z ##[debug]loading INPUT_FORCE
 
2018-09-19T14:20:27.2894236Z ##[debug]loading INPUT_ISMANDATORYUPDATE
 
2018-09-19T14:20:27.3050516Z ##[debug]loading INPUT_MANDATORYUPDATEDIFFERHOURS
 
2018-09-19T14:20:27.3050516Z ##[debug]loading INPUT_NAMETYPE
 
2018-09-19T14:20:27.3050516Z ##[debug]loading INPUT_NUMBEROFPACKAGESTOKEEP
 
2018-09-19T14:20:27.3050516Z ##[debug]loading INPUT_PACKAGEPATH
 
2018-09-19T14:20:27.3050516Z ##[debug]loading INPUT_SERVICEENDPOINT
 
2018-09-19T14:20:27.3050516Z ##[debug]loading INPUT_SKIPPOLLING
 
2018-09-19T14:20:27.3050516Z ##[debug]loaded 15
 
2018-09-19T14:20:27.5394273Z ##[debug]task result: Failed
 
2018-09-19T14:20:27.5706754Z ##[error]Unhandled: Unexpected token =

**Comment by zurdev** [comment]
It might be an issue with the configuration of "Windows Dev Center" Service Endpoint. Verify that you've entered correctly all the parameters. Comparing your log with a successful log, I'm seeing 20 inputs loaded compared with 15 inputs in your log. The missing inputs are related to Service Endpoint.

**Comment by elendil326** [comment]
I'm following up with the VSTS/TFS team on this issue. In the meantime, @mlowrancejha can you try creating a new endpoint and referencing it in the build definition? As @zurdev mentioned, the issue seems to be related to the endpoint itself, as the log seems to be loading two endpoints rather than only one.

**Comment by mlowrancejha** [comment]
@elendil326 Thanks for looking into this for me.  I had another user create an endpoint just to make sure I hadn't messed something up along the way and got the same result.

2018-10-01T18:32:16.8936664Z ##[error]Unhandled: Unexpected token =

Thanks!

**Comment by elendil326** [comment]
@mlowrancejha can you share the version of your TFS server?

**Comment by mlowrancejha** [comment]
@elendil326  I looked on the about page, it shows:

Microsoft Visual Studio Team Foundation Server
Version 14.102.25423.0

**Comment by elendil326** [comment]
Thanks @mlowrancejha . Can you also share the agent version? Also, it would be of big help if you could share the flight.js file under your agent directory (e.g. $(agent)\_work\_tasks\store-flight\flight.js)

**Comment by mlowrancejha** [comment]
Agent Version: 1.92.3

flightUI.js is attached.  It might be off spacing, etc a little, I had put some debug statements in there myself when I was trying to figure out what was wrong.  I removed them before attaching.

[flightUi.js.txt](https://github.com/Microsoft/windows-dev-center-vsts-extension/files/2447669/flightUi.js.txt)


Thanks

**Comment by elendil326** [comment]
Thanks for the info and for the patience so far while we investigate this issue. Since I can't repro the issue, I will need your help to do some diagnostics. We would want to nail down what is the component that is throwing the error and try to get a stack of it. Can you modify your file as below and then try a submission again, then please share the logs with us.

From:
```
const fli = require("./flight");
const path = require("path");
const tl = require("vsts-task-lib");
```

To:
```
const fli = require("./flight");
const path = require("path");
var tl = undefined;
try
{
    tl = require("vsts-task-lib");
}
catch (err) {
    if (err.stack != undefined) {
        console.error('=== Error stack ===');
        console.error(err.stack);
        console.error('=== End of stack ===');
    }
    console.error(err);
}
```

**Comment by mlowrancejha** [comment]
I have run it several times with the changes & even rebooted the server but I don't see any change in the log (below).

Is there something I need to do to the agent to get it to pick up the fact that the script has changed?



2018-10-08T14:11:35.2673487Z Set workingFolder to default: C:\agent2\tasks\store-flight\0.2.22\local
 
2018-10-08T14:11:36.0175310Z ##[debug]agent.workFolder=e:\builds\agent02
 
2018-10-08T14:11:36.0331650Z ##[debug]loading inputs and endpoints
 
2018-10-08T14:11:36.0331650Z ##[debug]loading ENDPOINT_AUTH_0C1AD030-561F-42A9-BB7E-7E0B8C32448A
 
2018-10-08T14:11:36.0331650Z ##[debug]loading ENDPOINT_AUTH_3306CACE-E67A-4512-AF8A-7D35E0E733D0
 
2018-10-08T14:11:36.0331650Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
 
2018-10-08T14:11:36.0331650Z ##[debug]loading INPUT_APPID
 
2018-10-08T14:11:36.0331650Z ##[debug]loading INPUT_DELETEPACKAGES
 
2018-10-08T14:11:36.0331650Z ##[debug]loading INPUT_FLIGHTNAME
 
2018-10-08T14:11:36.0331650Z ##[debug]loading INPUT_FORCE
 
2018-10-08T14:11:36.0331650Z ##[debug]loading INPUT_ISMANDATORYUPDATE
 
2018-10-08T14:11:36.0331650Z ##[debug]loading INPUT_MANDATORYUPDATEDIFFERHOURS
 
2018-10-08T14:11:36.0487892Z ##[debug]loading INPUT_NAMETYPE
 
2018-10-08T14:11:36.0487892Z ##[debug]loading INPUT_NUMBEROFPACKAGESTOKEEP
 
2018-10-08T14:11:36.0487892Z ##[debug]loading INPUT_PACKAGEPATH
 
2018-10-08T14:11:36.0487892Z ##[debug]loading INPUT_SERVICEENDPOINT
 
2018-10-08T14:11:36.0487892Z ##[debug]loading INPUT_SKIPPOLLING
 
2018-10-08T14:11:36.0487892Z ##[debug]loaded 14
 
2018-10-08T14:11:36.1894490Z ##[debug]task result: Failed
 
2018-10-08T14:11:36.1894490Z ##[error]Unhandled: Unexpected token =

**Comment by ericsciple** [comment]
@mlowrancejha you may want to add trace statements between each line, to narrow in. Something like:

```js
console.log('******************** BEFORE INPUT HELPER');
const inputHelper = require("../common/inputHelper");
console.log('******************** BEFORE FLIGHT');
const fli = require("./flight");
console.log('******************** BEFORE PATH');
const path = require("path");
console.log('******************** BEFORE TASK LIB');
const tl = require("vsts-task-lib");
console.log('******************** AFTER TASK LIB');
```

Make sure you are editing the js file and not the ts. The agent should pickup the changes on the very next build. The agent reads it from that disk location every time.

**Comment by mlowrancejha** [comment]
Thanks.

I added debug statements down through the files and figured out it is failing when it is trying to load the requesthelper.  I added some debug statements to it, but so far nothing has actually been written.  Below is the log, with the try/catch around the request helper and its stack trace.

Also attached is the requestHelper.js file.

I will keep adding debug statements as well to see if I can find anything else.


<br> <br>

10-08T19:21:53.1786662Z Set workingFolder to default: C:\agent2\tasks\store-flight\0.2.22\local
 
2018-10-08T19:21:53.3349160Z ******************** BEFORE INPUT HELPER
 
2018-10-08T19:21:53.4130416Z ##[debug]agent.workFolder=e:\builds\agent02
 
2018-10-08T19:21:53.4286655Z ##[debug]loading inputs and endpoints
 
2018-10-08T19:21:53.4286655Z ##[debug]loading ENDPOINT_AUTH_0C1AD030-561F-42A9-BB7E-7E0B8C32448A
 
2018-10-08T19:21:53.4286655Z ##[debug]loading ENDPOINT_AUTH_3306CACE-E67A-4512-AF8A-7D35E0E733D0
 
2018-10-08T19:21:53.4286655Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
 
2018-10-08T19:21:53.4286655Z ##[debug]loading INPUT_APPID
 
2018-10-08T19:21:53.4286655Z ##[debug]loading INPUT_DELETEPACKAGES
 
2018-10-08T19:21:53.4286655Z ##[debug]loading INPUT_FLIGHTNAME
 
2018-10-08T19:21:53.4286655Z ##[debug]loading INPUT_FORCE
 
2018-10-08T19:21:53.4286655Z ##[debug]loading INPUT_ISMANDATORYUPDATE
 
2018-10-08T19:21:53.4286655Z ##[debug]loading INPUT_MANDATORYUPDATEDIFFERHOURS
 
2018-10-08T19:21:53.4286655Z ##[debug]loading INPUT_NAMETYPE
 
2018-10-08T19:21:53.4286655Z ##[debug]loading INPUT_NUMBEROFPACKAGESTOKEEP
 
2018-10-08T19:21:53.4286655Z ##[debug]loading INPUT_PACKAGEPATH
 
2018-10-08T19:21:53.4286655Z ##[debug]loading INPUT_SERVICEENDPOINT
 
2018-10-08T19:21:53.4286655Z ##[debug]loading INPUT_SKIPPOLLING
 
2018-10-08T19:21:53.4286655Z ##[debug]loaded 14
 
2018-10-08T19:21:53.4442989Z ******************** BEFORE FLIGHT
 
2018-10-08T19:21:53.4442989Z ******************** BEFORE API
 
2018-10-08T19:21:53.4442989Z ******************** IN API
 
2018-10-08T19:21:53.4442989Z ******************** BEFORE requestHelper - API
 
2018-10-08T19:21:53.4442989Z === Error stack ===
 
2018-10-08T19:21:53.4442989Z SyntaxError: Unexpected token =
 
2018-10-08T19:21:53.4442989Z     at exports.runInThisContext (vm.js:53:16)
 
2018-10-08T19:21:53.4442989Z     at Module._compile (module.js:387:25)
 
2018-10-08T19:21:53.4442989Z     at Object.Module._extensions..js (module.js:422:10)
 
2018-10-08T19:21:53.4442989Z     at Module.load (module.js:357:32)
 
2018-10-08T19:21:53.4442989Z     at Function.Module._load (module.js:314:12)
 
2018-10-08T19:21:53.4442989Z     at Module.require (module.js:367:17)
 
2018-10-08T19:21:53.4442989Z     at require (internal/module.js:16:19)
 
2018-10-08T19:21:53.4442989Z     at Object.<anonymous> (C:\agent2\tasks\store-flight\0.2.22\common\apiHelper.js:24:11)
 
2018-10-08T19:21:53.4442989Z     at Module._compile (module.js:413:34)
 
2018-10-08T19:21:53.4442989Z     at Object.Module._extensions..js (module.js:422:10)
 
2018-10-08T19:21:53.4442989Z === End of stack ===
 
2018-10-08T19:21:53.4442989Z [SyntaxError: Unexpected token =]
 
2018-10-08T19:21:53.4599154Z ******************** fs - API
 
2018-10-08T19:21:53.4599154Z ******************** path - API
 
2018-10-08T19:21:53.4599154Z ******************** jszip - API
 
2018-10-08T19:21:54.1786728Z ******************** q
 
2018-10-08T19:21:54.1786728Z ******************** vsts-task-lib - API
 
2018-10-08T19:21:54.1786728Z ******************** azure-storage - API
 
2018-10-08T19:21:56.1318183Z ******************** BEFORE url - API
 
2018-10-08T19:21:56.1318183Z ******************** After API requires
 
2018-10-08T19:21:56.1318183Z ******************** BEFORE Request Helper
 
2018-10-08T19:21:56.1318183Z ##[debug]task result: Failed
 
2018-10-08T19:21:56.1318183Z ##[error]Unhandled: Unexpected token =



[requestHelper.js.txt](https://github.com/Microsoft/windows-dev-center-vsts-extension/files/2457414/requestHelper.js.txt)

**Comment by mlowrancejha** [comment]
I removed methods from requestHelper one at a time and figured out the error was in this method:

`function isRetryableError(err, relax = true) {
    // Does this look like a ResponseInformation?
    if (err != undefined && err.response != undefined && typeof err.response.statusCode == 'number') {
        return err.response.statusCode == 429 // 429 code is returned by the API for throttle down. This is retriable
            || err.response.statusCode == 503
            || (relax && err.response.statusCode >= 500);
    }
    // Default to retry if no err information.
    return true;
}
exports.isRetryableError = isRetryableError;`

When I removed the "= true" from relax in the function definition the build moved on successfully.  I'm not sure why that default parameter wouldn't work...

Anyway, I think I'm moving ahead, I'm going to leave this open and I'll come back and close it once I finish the process.

Thanks for all the help!

**Comment by ericsciple** [comment]
@mlowrancejha i'm guessing your agent version is less than 2.117.0? [That is when](https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/minagent.md#task-execution-handler) we switched from node 5.10.1 to node 6.10.3.

@elendil326 Node 5 was mostly ES6 compliant, but falls apart in some places. I'm guessing this is one place.

**Comment by mlowrancejha** [comment]
Yes, still on 1.95.3.  

I think this has gotten me past this issue, so I'm going to go ahead and close it.  Thanks again for all the help!
